### ISSUE TITLE
String hashing performance is very slow

### ISSUE THREAD

**Issue by silo-oevans** [neuml/py27hash#4]
https://github.com/neuml/py27hash/blob/master/src/python/py27hash/hash.py#L144

```
        for c in value:
            x = (1000003 * x) ^ Hash.ordinal(c)

```
x can become very large and is only truncated back to 64 bits after the entire string is hashed
There is no reason full precision must be maintained for the entire loop. It can be truncated back to 64 bits after eatch iteration

**Comment by davidmezzetti** [comment]
#5 partially addresses this issue but isn't fast enough for the problem at hand. Will keep this issue open in case a pure Python fix becomes available.

**Comment by musicinmybrain** [comment]
I think it’s worth considering something similar to #5 even if it doesn’t obtain the large-string performance the original requestor wanted.

Masking with `0xffffffffffffffff` in the inner loop has the following advantages:

- It keeps operations faster by allowing the interpreter to avoid arbitrary-precision integer math, especially on 64-bit hosts where the product fits in a native word
- It keeps string hashing runtime linear in the length of the string

It’s a small distinction, but I would favor masking before rather than after the xor. This might or might not make things a little faster on 32-bit hosts (I haven’t tested), and has no downside. I would also still mask the length at the end since the cost is negligible (based on benchmarks) and this keeps the routine easy to reason about.

I would write something like:

```python
        mask = 0xffffffffffffffff
        x = (Hash.ordinal(value[0]) << 7) & mask
        for c in value:
            x = (1000003 * x) & mask ^ Hash.ordinal(c)

        x ^= length & mask
```

In my tests on a fast `x86_64` processor with Python 3.10, this reduces the runtime for the existing test suite (with slow tests) from about 80 seconds to 30 seconds, and I can’t see any disadvantages.

**Comment by musicinmybrain** [comment]
By the way, I am not sure this is right:

```python
        if x == -1:
            x = -2
```

Consider that `-1 & 0xffffffffffffffff` is 18446744073709551615, or 0xffffffffffffffff. That is, since masking has already taken place, I think `x` is guaranteed to be nonnegative here, and this should actually be:



```python
        if x == 0xffffffffffffffff:
            x = -2  # or, equivalently, 0xfffffffffffffffe
```

to have the effect that seems to be intended.

**Comment by musicinmybrain** [comment]
On pypy 7.3.8, which benefits from JIT, the difference is even more dramatic: the test suite runtime goes from about 80 seconds to less than five.

**Comment by davidmezzetti** [comment]
What would you recommend? The patch as is?

**Comment by musicinmybrain** [comment]
Please consider: https://github.com/neuml/py27hash/pull/7

**Comment by davidmezzetti** [comment]
#7 merged to handle this issue, thank you for the PRs!
